[project]
name = "risk-reliability"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Masaru Kitahara", email = "kitahara@eng.hokudai.ac.jp" }
]
requires-python = ">=3.13"
dependencies = [
    "marimo>=0.25.1",
    "matplotlib>=3.11.2",
    "numpy>=2.5.3",
    "scipy>=1.18.1",
]

[project.scripts]
risk-reliability = "risk_reliability:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
